---
version: "2"
services:
  ferdi-server:
    image: getferdi/ferdi-server
    container_name: $SERVICE
    environment:
      - NODE_ENV=$NODE_ENV
      - EXTERNAL_DOMAIN=$NDD	 
      - DB_CONNECTION=$DB_DRIVER
      - DB_HOST=$DB_HOST
      - DB_PORT=$DB_PORT
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
      - DB_DATABASE=$DB_DATABASE
      - DB_SSL=$DB_SSL
      - MAIL_CONNECTION=$MAIL_CONNECTION
      - SMPT_HOST=$SMPT_HOST
      - SMTP_PORT=$SMTP_PORT
      - MAIL_SSL=$MAIL_SSL
      - MAIL_USERNAME=$MAIL_USERNAME
      - MAIL_PASSWORD=$MAIL_PASSWORD
      - MAIL_SENDER=$MAIL_SENDER
      - IS_CREATION_ENABLED=$IS_CREATION_ENABLED
      - IS_DASHBOARD_ENABLED=$IS_DASHBOARD_ENABLED
      - IS_REGISTRATION_ENABLED=$IS_REGISTRATION_ENABLED
      - CONNECT_WITH_FRANZ=$CONNECT_WITH_FRANZ
    volumes:
      - $DATA_LOCATION:/config
      - $DATA_LOCATION:/app/database
      - $DATA_LOCATION:/app/recipes
    ports:
      - 8080:80
    restart: unless-stopped