# Docker-compose mis à disposition par Kevin Allioli
# Date de mise à jour : 28/04/2021

# Variables d'environnement à déclarer :
#     - SERVICE : nom du service (exemple : hastebin)
#     - DATA_LOCATION : localisation des données (exemple /apps/"service")
#     - URL_LOKI : lien du serveur loki (exemple : ndd/loki/api/v1/push)
#     - NDD : lien du nom de domaine
#     - NETWORK_APP : nom du réseau applicatif

# Fonctionne avec Portainer
version: "2"
services:
  hastebin:
    image: rlister/hastebin
    container_name: $SERVICE
    restart: always
    environment:
      STORAGE_TYPE: file
    volumes:
      - $DATA_LOCATION/data:/data  
    networks:
      - default
    logging:
      driver: loki
      options:
        loki-url: "$URL_LOKI"
        loki-external-labels: service={{.Name}}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.$SERVICE.entrypoints=https"
      - "traefik.http.routers.$SERVICE.rule=Host(`$NDD`)"
      - "traefik.http.services.$SERVICE.loadbalancer.server.port=7777"
      - "traefik.docker.network=$NETWORK_APP"
      
networks:
  default:
    external:
      name: $NETWORK_APP