# Docker-compose mis à disposition par Kevin Allioli
# Date de mise à jour : 27/04/2021

# Variables d'environnement à déclarer :
#     - SERVICE : nom du service (exemple : mariadb)
#     - POSTGRES_HOST : nom du conteneur PostgreSQL
#     - POSTGRES_DB : nom de la base de donnée 
#     - POSTGRES_USER : nom de l'utilisateur 
#     - POSTGRES_PASSWORD : Mot de passe de la base de donnée
#     - NEXTCLOUD_ADMIN_USER : utilisateur administrateur nextcloud
#     - NEXTCLOUD_ADMIN_PASSWORD : mot de passe administrateur nextcloud
#     - NEXTCLOUD_TRUSTED_DOMAINS : nom de domaines autorisés dans nextcloud
#     - URL_LOKI : adresse du service loki
#     - DATA_LOCATION : emplacement des données du service
#     - NDD : Nom de domaine de l'application
#     - NETWORK_APP : nom du réseau applicatif
#     - NETWORK_DATA : nom du réseau data

# Fonctionne avec Portainer

version: '2'
services:
  nextcloud:
    container_name: $SERVICE
    image: nextcloud
    restart: always
    environment:
      - POSTGRES_HOST=$POSTGRES_HOST
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - NEXTCLOUD_ADMIN_USER=$NEXTCLOUD_ADMIN_USER
      - NEXTCLOUD_ADMIN_PASSWORD=$NEXTCLOUD_ADMIN_PASSWORD
      - NEXTCLOUD_TRUSTED_DOMAINS=$NEXTCLOUD_TRUSTED_DOMAINS
    logging:
      driver: loki
      options:
        loki-url: "$URL_LOKI"
        loki-external-labels: service={{.Name}}
    volumes:
      - $DATA_LOCATION:/var/www/html
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.$SERVICE.entrypoints=https"
      - "traefik.http.routers.$SERVICE.rule=Host(`$NDD`)"
      - "traefik.http.services.$SERVICE.loadbalancer.server.port=80"
      - "traefik.docker.network=$NETWORK_APP"
    networks:
      - default
      - default1

networks:
  default:
    external:
      name: $NETWORK_APP
  default1:
    external:
      name: $NETWORK_DATA
    