# Docker-compose mis à disposition par Kevin Allioli
# Date de mise à jour : 15/03/2021

# Variables d'environnement à déclarer :
#     - SERVICE : nom du service (exemple : pgadmin)
#     - EMAIL : email utilisateur admin
#     - PASSWORD : Mot de passe de l'administrateur
#     - DATA_LOCATION : localisation des données (exemple /apps/"service")
#     - NDD : nom de domaine de l'application
#     - NETWORK_APP : nom du réseau du conteneur
#     - NETWORK_DATA : nom du réseau du conteneur

# Fonctionne avec Portainer

version: "2"
services:
  pgadmin:
    image: dpage/pgadmin4
    container_name: $SERVICE
    environment:
      - PGADMIN_DEFAULT_EMAIL=$EMAIL
      - PGADMIN_DEFAULT_PASSWORD=$PASSWORD
      - PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION="True"
      - PGADMIN_CONFIG_CONSOLE_LOG_LEVEL=10
    healthcheck:
      test: wget -nv -t1 --spider 'http://localhost:80/misc/ping'
      interval: 1m
      timeout: 30s
      retries: 3
    logging:
      driver: loki
      options:
        loki-url: "$URL_LOKI"
        loki-external-labels: service={{.Name}}
    restart: unless-stopped
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.$SERVICE.entrypoints=https"
    - "traefik.http.routers.$SERVICE.rule=Host(`$NDD`)"
    - "traefik.http.services.$SERVICE.loadbalancer.server.port=80"
    - "traefik.docker.network=$NETWORK_APP"
    volumes:
      - /srv/docker-data/pgadmin:/var/lib/pgadmin
    networks:
      - default
      - default1

networks:
  default:
    external:
      name: $NETWORK_APP
  default1:
    external:
       name: $NETWORK_DATA
