# Docker-compose mis à disposition par Kevin Allioli
# Date de mise à jour : 13/03/2021

# Variables d'environnement à déclarer :
#     - SERVICE : nom du service (exemple : plex)
#     - VERSION : version à déployée (exemple : latest)
#     - PUID : uid de de l'utilisateur système (exemple : 1001)
#     - GUID : Gid de du groupe système (exemple : 1001)
#     - TZ : Timezone du service (exemple : Europe/Paris)
#     - CONFIG_DATA_LOCATION : localisation des données de configuration 
#     - MOVIES_DATA_LOCATION : localisation des films
#     - TVSHOWS_DATA_LOCATION : localisation des séries
#     - PHOTOS_DATA_LOCATION : localisation des photos
#     - WEBINARS_DATA_LOCATION : localisation des webinars 
#     - TRANSCODE_DATA_LOCATION : dossier temporaire pour le transcodage
#     - TRANSCODE_DEVICE : périphérique utilisé pour le transcodage

# Fonctionne avec Portainer

version: '2'
services:
  plex:
    image: ghcr.io/linuxserver/plex
    container_name: $SERVICE
    restart: always
    network_mode: host
    environment:
      - VERSION=$VERSION
      - PUID=$PUID
      - PGID=$GUID
      - TZ=$TZ
    volumes:
      - $CONFIG_DATA_LOCATION:/config
      - $MOVIES_DATA_LOCATION:/data/movies
      - $TVSHOWS_DATA_LOCATION:/data/tvshows
      - $PHOTOS_DATA_LOCATION:/data/photos
      - $WEBINARS_DATA_LOCATION:/data/webinars
      - $TRANSCODE_DATA_LOCATION:/transcode
    devices:
      - $TRANSCODE_DEVICE:/dev/dri
