# Docker-compose provided by Kevin Allioli
# Last update : 07/12/2021

# Environment variables to declare :
#     - SERVICE : name of the service (example : bing-wallpaper)
#     - URL_LOKI : loki service URL (example : http://ip:3100/loki/api/v1/push)
#     - FQDN : fully qualified domain name (example : bing.domain.tld)
#     - NETWORK_APP : application network name

# Work with Portainer

version: '3.3'
services:
  uptime-kuma:
    image: linitio/bing-wallpaper
    container_name: $SERVICE
    restart: unless-stopped
    healthcheck:
      test: wget -nv -t1 --spider 'http://localhost:9000'
      interval: 1m
      timeout: 30s
      retries: 3
    logging:
      driver: loki
      options:
        loki-url: "$URL_LOKI"
        loki-external-labels: service={{.Name}}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.$SERVICE.entrypoints=https"
      - "traefik.http.routers.$SERVICE.rule=Host(`$FQDN`)"
      - "traefik.http.services.$SERVICE.loadbalancer.server.port=9000"
      - "traefik.docker.network=$NETWORK_APP"
    networks:
      - default

networks:
  default:
    external:
      name: $NETWORK_APP
