# Docker-compose mis à disposition par Kevin Allioli
# Date de mise à jour : 17/03/2021

# Variables d'environnement à déclarer :
#     - SERVICE : nom du service (exemple : mariadb)
#     - DATA_LOCATION : localisation des données (exemple /apps/"service")
#     - JSON_CONFIG_FILE : chemin du fichier config.json
#     - DB_FILE : chemin du fichier database.db
#     - FQDN : Nom de domaine de l'application
#     - NETWORK_APP : nom du réseau applicatif

# Fonctionne avec Portainer

version: "3.3"
services:
  filebrowser:
    image: filebrowser/filebrowser:s6
    container_name: $SERVICE
    restart: unless-stopped
    environment:
      - PUID=$PUID
      - PGID=$PGID
    healthcheck:
      test: wget -nv -t1 --spider 'http://localhost:80'
      interval: 1m
      timeout: 30s
      retries: 3
    logging:
      driver: loki
      options:
        loki-url: "$URL_LOKI"
        loki-external-labels: service={{.Name}}
    volumes:
      - $DATA_LOCATION:/srv
      - $JSON_CONFIG_FILE:/config.json
      - $DB_FILE:/database.db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.$SERVICE.entrypoints=https"
      - "traefik.http.routers.$SERVICE.rule=Host(`$FQDN`)"
      - "traefik.http.services.$SERVICE.loadbalancer.server.port=80"
      - "traefik.docker.network=$NETWORK_APP"
    networks:
      - default

networks:
  default:
    external:
      name: ${NETWORK_APP}
