# Docker-compose provided by Kevin Allioli
# Last update : 24/12/2021

# Environment variables to declare :
#     - SERVICE : name of the service (example : freshrss)
#     - CRON : time between cron job fo sync news (example : */20)
#     - TZ : container time zone (example : Europe/Paris)
#     - DATA_LOCATION : location of service data (example /app/"service")
#     - URL_LOKI : loki service URL (example : http://ip:3100/loki/api/v1/push)
#     - FQDN : fully qualified domain name (example : hastebin.domain.tld)
#     - NETWORK_APP : application network name
#     - NETWORK_DATA : Data network name


# Work with Portainer

---
version: "2.1"
services:
  freshrss:
    image: freshrss/freshrss:latest
    container_name: $SERVICE
    restart: unless-stopped
    environment:
      - CRON_MIN: '$CRON'
      - TZ: $TZ
    logging:
      driver: loki
      options:
        loki-url: "$URL_LOKI"
        loki-external-labels: service={{.Name}}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.$SERVICE.entrypoints=https"
      - "traefik.http.routers.$SERVICE.rule=Host(`$FQDN`)"
      - "traefik.http.services.$SERVICE.loadbalancer.server.port=80"
      - "traefik.docker.network=$NETWORK_APP"
    volumes:
      - $DATA_LOCATION/data:/var/www/FreshRSS/data
      - $DATA_LOCATION/extensions:/var/www/FreshRSS/extensions
    networks:
      - default
      - default1

networks:
  default:
    external:
      name: $NETWORK_APP
  default1:
    external:
      name: $NETWORK_DATA

