# Docker-compose provided by Kevin Allioli
# Last update : 18/03/2022

# Environment variables to declare :

#     - SERVICE : name of the service (example : grafana)
#     - PUID : uid de l'utilisateur système (exemple : 1001)
#     - DATA_LOCATION : location of service data (example /app/"service")
#     - FQDN : fully qualified domain name (example : hastebin.domain.tld)
#     - NETWORK_APP : application network name

# Work with Portainer

version: '2' 
services:
  grafana:
    image: grafana/grafana
    container_name: $SERVICE
    user: "$PUID"
    volumes:
      - $DATA_LOCATION/data:/var/lib/grafana
      - $DATA_LOCATION/config:/etc/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=$ADMIN_PASSWD
      - GF_PANELS_DISABLE_SANITIZE_HTML=true
      - GF_INSTALL_PLUGINS=grafana-piechart-panel,grafana-worldmap-panel,alexanderzobnin-zabbix-app
      - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=alexanderzobnin-zabbix-datasource
      - GF_SERVER_DOMAIN=$FQDN
      - GF_SERVER_ROOT_URL=https://$FQDN
    healthcheck:
      test: wget -nv -t1 --spider 'http://localhost:3000/'
      interval: 1m
      timeout: 30s
      retries: 3
    logging:
      driver: loki
      options:
        loki-url: "$URL_LOKI"
        loki-external-labels: service={{.Name}}
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.entrypoints=https"
      - "traefik.http.routers.grafana.rule=Host(`$FQDN`)"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"
      - "traefik.docker.network=$NETWORK_APP"
    networks:
      - default

networks:
  default:
    external:
      name: ${NETWORK_APP}