
version: "3"
services:
  homer:
    image: b4bz/homer
    container_name: $SERVICE
    restart: unless-stopped
    environment:
      - UID=$PUID
      - GID=$PGID
    #healthcheck:
    #  test: wget --spider 'https://localhost:443' --no-check-certificate
    #  interval: 1m
    #  timeout: 30s
    #  retries: 3
    logging:
      driver: loki
      options:
        loki-url: "$URL_LOKI"
        loki-external-labels: service={{.Name}}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.$SERVICE.entrypoints=https"
      - "traefik.http.routers.$SERVICE.rule=Host(`$FQDN`)"
      - "traefik.http.services.$SERVICE.loadbalancer.server.port=8080"
      - "traefik.docker.network=$NETWORK_APP"
    volumes:
      - $DATA_LOCATION:/www/assets
    networks:
      - default

networks:
  default:
    external:
      name: ${NETWORK_APP}