# Docker-compose provided by Kevin Allioli
# Last update : 18/03/2022

# Environment variables to declare :
#     - SERVICE : service name (example : loki)
#     - FQDN : fully qualified domain name (example : loki.domain.tld
#     - NETWORK_APP : application network name
#     - NETWORK_DATA : data network name

# Work with portainer

version: "3.3"
services:
  loki:
    image: grafana/loki:latest
    container_name: $SERVICE
    restart: unless-stopped
    command: -config.file=/etc/loki/local-config.yaml
    healthcheck:
      test: nc -z 127.0.0.1 3100 || exit 1
      interval: 1m
      timeout: 30s
      retries: 3
    volumes: 
      - $DATA_LOCATION/config/loki-config.yaml:/etc/loki/loki-config.yaml
      - $DATA_LOCATION/data:/data/loki
    networks:
      - default
      - default1
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.$SERVICE.entrypoints=https"
      - "traefik.http.routers.$SERVICE.rule=Host(`$FQDN`)"
      - "traefik.http.services.$SERVICE.loadbalancer.server.port=3100"
      - "traefik.docker.network=$NETWORK_APP"

  promtail:
    image: grafana/promtail:1.5.0
    container_name: $SERVICE_PROMTAIL
    restart: always
    healthcheck:
      test: grep -q "promtail" /proc/1/status || exit 1
      interval: 1m
      timeout: 30s
      retries: 3
    volumes:
      - /var/log:/var/log
    command: -config.file=/etc/promtail/docker-config.yaml
    networks:
      - default

networks:
  default:
    external:
      name: ${NETWORK_APP}
  default1:
    external:
      name: ${NETWORK_DATA}