# Docker-compose provided by Kevin Allioli
# Last update : 15/03/2022

# Environment variables to declare :
#     - SERVICE : name of the service (example : phpmyadmin)
#     - URL_LOKI : loki service URL (example : http://ip:3100/loki/api/v1/push)
#     - DATA_LOCATION : location of service data (example /app/"service")
#     - FQDN : fully qualified domain name (example : pma.domain.tld)
#     - NETWORK_APP : application network name
#     - NETWORK_DATA : database network name

# Work with Portainer

version: "3.3"
services:
  phpmyadmin:
    image: phpmyadmin
    container_name: $SERVICE
    environment:
      - PMA_ARBITRARY=1
    healthcheck:
      test: curl --fail http://localhost:80 || exit 1
      interval: 1m
      timeout: 30s
      retries: 3
    logging:
      driver: loki
      options:
        loki-url: "$URL_LOKI"
        loki-external-labels: service={{.Name}}
    volumes:
      - $DATA_LOCATION:/sessions
    restart: unless-stopped
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.$SERVICE.entrypoints=https"
    - "traefik.http.routers.$SERVICE.rule=Host(`$FQDN`)"
    - "traefik.http.services.$SERVICE.loadbalancer.server.port=80"
    - "traefik.docker.network=$NETWORK_APP"
    networks:
      - default
      - default1

networks:
  default:
    external:
      name: ${NETWORK_APP}
  default1:
    external:
       name: ${NETWORK_DATA}