# Docker-compose provided by Kevin Allioli
# Last update : 05/05/2021

# Environment variables to declare :
#     - SERVICE : name of the service (example : plex)
#     - VERSION : deployed version (example : latest)
#     - PUID : system user id (example : 1001)
#     - PGID : system group id (example : 1001)
#     - TZ : container time zone (example : Europe/Paris)
#     - CONFIG_DATA_LOCATION : location of configuration service data (example /app/"service")
#     - DATA_LOCATION : location of service data (example /app/"service")
#     - TRANSCODE_DATA_LOCATION : data transcode location 
#     - TRANSCODE_DEVICE : device used for transcoding

# Work with Portainer

version: '2'
services:
  plex:
    image: ghcr.io/linuxserver/plex
    container_name: $SERVICE
    restart: always
    environment:
      - VERSION=$VERSION
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    healthcheck:
      test: curl --connect-timeout 15 --max-time 100 --silent --show-error --fail "http://localhost:32400/identity" > /dev/null
      interval: 1m
      timeout: 30s
      retries: 3
    logging:
      driver: loki
      options:
        loki-url: "$URL_LOKI"
        loki-external-labels: service={{.Name}}
    volumes:
      - $CONFIG_DATA_LOCATION:/config
      - $DATA_LOCATION:/data
      - $TRANSCODE_DATA_LOCATION:/transcode
    network_mode: host
    devices:
      - $TRANSCODE_DEVICE:/dev/dri