# Docker-compose provided by Kevin Allioli
# Last update : 03/05/2021

# Environment variables to declare :
#     - SERVICE : name of the service (example : mariadb)
#     - DB_ROOT_PASS : passord of postgres user
#     - URL_LOKI : loki service URL (example : http://ip:3100/loki/api/v1/push)
#     - DATA_LOCATION : location of service data (example /app/"service")
#     - NETWORK_DATA : data network name

# Work with Portainer

version: "2"
services:
  postgresql: 
    image: postgres:13-alpine
    container_name: $SERVICE
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=$DB_ROOT_PASS
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    logging:
      driver: loki
      options:
        loki-url: "$URL_LOKI"
        loki-external-labels: service={{.Name}}
    volumes:
      - $DATA_LOCATION:/var/lib/postgresql/data
    networks:
      - default

networks:
  default:
    external:
      name: $NETWORK_DATA