# Docker-compose provided by Kevin Allioli
# Last update : 22/05/2021

# Environment variables to declare :
#     - SERVICE : name of the service (example : pyload)
#     - PUID : system user id (example : 1001)
#     - PGID : system group id (example : 1001)
#     - TZ : container time zone (example : Europe/Paris)
#     - URL_LOKI : loki service URL (example : http://ip:3100/loki/api/v1/push)
#     - FQDN : fully qualified domain name (example : kanboard.domain.tld)
#     - CONFIG_DATA_LOCATION : location of service configuration data (example /app/"service")
#     - DOWNLOAD_DATA_LOCATION : files downloaded location (example /app/"service")
#     - NETWORK_APP : application network name

# Work with Portainer

version: "2.1"
services:
  pyload:
    image: ghcr.io/linuxserver/pyload
    container_name: $SERVICE
    restart: always
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    healthcheck:
      test: curl --fail http://localhost:8000 || exit 1
      interval: 1m
      timeout: 30s
      retries: 3
    logging:
      driver: loki
      options:
        loki-url: "$URL_LOKI"
        loki-external-labels: service={{.Name}}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.$SERVICE.entrypoints=https"
      - "traefik.http.routers.$SERVICE.rule=Host(`$FQDN`)"
      - "traefik.http.services.$SERVICE.loadbalancer.server.port=8000"
      - "traefik.docker.network=$NETWORK_APP"
    volumes:
      - $CONFIG_DATA_LOCATION:/config
      - $DOWNLOAD_DATA_LOCATION:/downloads
    ports:
      - 7227:7227
    networks:
      - default

networks:
  default:
    external:
      name: $NETWORK_APP