# Docker-compose provided by Kevin Allioli
# Last update : 20/05/2021

# Environment variables to declare :
#     - SERVICE : name of the service (example : kanboard)
#     - PUID : system user id (example : 1001)
#     - PGID : system group id (example : 1001)
#     - TZ : container time zone (example : Europe/Paris)
#     - URL_LOKI : loki service URL (example : http://ip:3100/loki/api/v1/push)
#     - FQDN : fully qualified domain name (example : kanboard.domain.tld)
#     - DATA_LOCATION : location of service data (example /app/"service")
#     - NETWORK_APP : application network name

# Work with Portainer

version: "2.1"
services:
  qbittorrent:
    image: ghcr.io/linuxserver/qbittorrent
    container_name: $SERVICE
    restart: unless-stopped
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - WEBUI_PORT=8080
    healthcheck:
      test: curl --fail http://localhost:8080 || exit 1
      interval: 1m
      timeout: 30s
      retries: 3
    logging:
      driver: loki
      options:
        loki-url: "$URL_LOKI"
        loki-external-labels: service={{.Name}}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.$SERVICE.entrypoints=https"
      - "traefik.http.routers.$SERVICE.rule=Host(`$FQDN`)"
      - "traefik.http.services.$SERVICE.loadbalancer.server.port=8080"
      - "traefik.docker.network=$NETWORK_APP"
    ports:
      - 6881:6881
      - 6881:6881/udp
    volumes:
      - $DATA_LOCATION/config:/config
      - $DATA_LOCATION/downloads:/downloads
    networks:
      - default

networks:
  default:
    external:
      name: $NETWORK_APP