# Docker-compose provided by Kevin Allioli
# Last update : 16/03/2022

# Environment variables to declare :
#     - SERVICE : name of the service (example : redis)
#     - URL_LOKI : loki service URL (example : http://ip:3100/loki/api/v1/push)
#     - DATA_LOCATION : location of service data (example /app/"service")
#     - NETWORK_DATA : Data network name

# Work with Portainer

version: '3'
services:
  redis:
    image: redis:latest
    container_name: $SERVICE
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 30
    logging:
      driver: loki
      options:
        loki-url: "$URL_LOKI"
        loki-external-labels: service={{.Name}}
    volumes:
      - $DATA_LOCATION/data:/data
    networks:
      - default

networks:
  default:
    name: ${NETWORK_DATA}