# Docker-compose provided by Kevin Allioli
# Last update : 15/00/2022

# Environment variables to declare :
#     - SERVICE : name of the service (example : mariadb)
#     - SMARTHOST : fqdn of the final mail server (example : mail.hostname.tld:port)
#     - STRING_CON: connection string to authenticate smtp relay on the final mail server  (example: hostname:user:password)
#     - ALLOWED_SENDERS : authorized networks for sending (example : 172.16.0.0/24)
#     - LIMIT_SIZE : message limit size (example : 25m)
#     - URL_LOKI : loki service URL (example : http://ip:3100/loki/api/v1/push)
#     - NETWORK_APP : application network name

# Work with Portainer

version: "2"
services:
  smtp-relay:
    image: linitio/mail-gateway
    container_name: $SERVICE
    restart: unless-stopped
    environment:
      - EXIM_SMARTHOST=$SMARTHOST
      - EXIM_PASSWORD=$STRING_CON
      - EXIM_ALLOWED_SENDERS=$ALLOWED_SENDER
      - EXIM_MESSAGE_SIZE_LIMIT=$LIMIT_SIZE
    healthcheck:
      test: echo -n "" | nc -q 1 127.0.0.1 25
      interval: 1m
      timeout: 30s
      retries: 3
    logging:
      driver: loki
      options:
        loki-url: "$URL_LOKI"
        loki-external-labels: service={{.Name}}
    networks:
      - default

networks:
  default:
    external:
      name: ${NETWORK_APP}