# Docker-compose provided by Kevin Allioli
# Last update : 08/10/2021

# Environment variables to declare :
#     - SERVICE : name of the service (example : hastebin)
#     - TZ : service timezone (example : Europe/Paris)
#     - DATA_LOCATION : location of service data (example /app/"service")
#     - URL_LOKI : loki service URL (example : http://ip:3100/loki/api/v1/push)
#     - FQDN : fully qualified domain name (example : hastebin.domain.tld)
#     - NETWORK_APP : application network name

# Work with Portainer

version: "2"
services:
  unms:
    image: nico640/docker-unms:latest
    container_name: $SERVICE
    restart: unless-stopped
    environment:
      - TZ=$TZ
    healthcheck:
      test: wget -s 'http://localhost:443'
      interval: 1m
      timeout: 30s
      retries: 3
    logging:
      driver: loki
      options:
        loki-url: "$URL_LOKI"
        loki-external-labels: service={{.Name}}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.$SERVICE.entrypoints=https"
      - "traefik.http.routers.$SERVICE.rule=Host(`$FQDN`)"
      - "traefik.http.services.$SERVICE.loadbalancer.server.port=443"
      - "traefik.docker.network=$NETWORK_APP"
    volumes:
      - $DATA_LOCATION:/config
    ports:
      - 2055:2055/udp
    networks:
      - default

networks:
  default:
    external:
      name: $NETWORK_APP