# Docker-compose provided by Kevin Allioli
# Last update : 08/05/2021

# Environment variables to declare :
#     - SERVICE : name of the service (example : zabbix-cachethq)
#     - URL_LOKI : loki service URL (example : http://ip:3100/loki/api/v1/push)
#     - DATA_LOCATION : location of service data (example /app/"service")
#     - NETWORK_APP : application network name

# Work with Portainer

version: "3"
services:
  # zabbix-cachet script : https://github.com/qk4l/zabbix-cachet
  zabbix-cachet:
    image: qk4l/zabbix-cachet
    container_name: $SERVICE
    restart: always
    logging:
      driver: loki
      options:
        loki-url: "$URL_LOKI"
        loki-external-labels: service={{.Name}}
    volumes:
      - $DATA_LOCATION/config/config.yml:/config.yml
    networks:
      - default
      
networks:
  default:
    external:
      name: app-network