# Docker-compose provided by Kevin Allioli
# Last update : 11/05/2022

# Environment variables to declare :
#     - SERVICE : service name (example : zabbix)
#     - DATA_LOCATION : location of service data (example /app/"service")
#     - URL_LOKI : loki service URL (example : http://ip:3100/loki/api/v1/push)
#     - FQDN : fully qualified domain name (example : yourls.domain.tld)
#     - NETWORK_APP : application network name
#     - NETWORK_DATA : data network name

# Work with Portainer


version: "3.3"
services:
  postgres-server:
    image: postgres:14.2
    restart: unless-stopped
    container_name: $SERVICE-db
    environment:
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
      POSTGRES_DB: zabbix
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256"
      PG_DATA: /var/lib/postgresql/data/pgdata
    volumes:
      - $DATA_LOCATION/zabbix/postgresql:/var/lib/postgresql/data
    networks:
      - default1

  zabbix-server:
    image: zabbix/zabbix-server-pgsql:6.0-ubuntu-latest 
    restart: unless-stopped
    container_name: $SERVICE-server
    environment:
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
      POSTGRES_DB: zabbix
      ZBX_HISTORYSTORAGETYPES: log,text #Zabbix configuration variables
      ZBX_DEBUGLEVEL: 1
      ZBX_HOUSEKEEPINGFREQUENCY: 1
      ZBX_MAXHOUSEKEEPERDELETE: 5000
      ZBX_STARTVMWARECOLLECTORS: 10
      ZBX_VMWAREFREQUENCY: 30
      ZBX_VMWAREPERFFREQUENCY: 30
      ZBX_VMWARECACHESIZE: 16M
      ZBX_VMWARETIMEOUT: 10
      ZBX_CACHESIZE: 2G
    healthcheck:
      test: grep -qr "zabbix_server" /proc/*/status || exit 1
      interval: 1m
      timeout: 30s
      retries: 3
    logging:
      driver: loki
      options:
        loki-url: "$URL_LOKI"
        loki-external-labels: service={{.Name}}
    depends_on:
      - postgres-server
    ports:
      - 10051:10051
    volumes:
      - $DATA_LOCATION/zabbix/config:/etc/zabbix/
      - $DATA_LOCATION/zabbix/alertscripts:/usr/lib/zabbix/alertscripts
    networks:
      - default
      - default1

  zabbix-web:
    image: zabbix/zabbix-web-nginx-pgsql:6.0-ubuntu-latest
    restart: unless-stopped
    container_name: $SERVICE-web
    environment:
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
      POSTGRES_DB: zabbix
      ZBX_SERVER_HOST: zabbix-server
      ZBX_POSTMAXSIZE: 64M
      PHP_TZ: "$TZ"
      ZBX_MAXEXECUTIONTIME: 500
    healthcheck:
      test: curl --fail http://localhost:8080 || exit 1
      interval: 1m
      timeout: 30s
      retries: 3
    logging:
      driver: loki
      options:
        loki-url: "$URL_LOKI"
        loki-external-labels: service={{.Name}}
    depends_on:
      - zabbix-server
    depends_on:
      - postgres-server
      - zabbix-server
    networks:
      - default
      - default1
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.$SERVICE.entrypoints=https"
      - "traefik.http.routers.$SERVICE.rule=Host(`$FQDN`)"
      - "traefik.http.services.$SERVICE.loadbalancer.server.port=8080"
      - "traefik.docker.network=$NETWORK_APP"

networks:
  default:
    external:
      name: $NETWORK_APP
  default1:
    external:
      name: $NETWORK_DATA
