# Docker-compose provided by Kevin Allioli
# Last update : 21/08/2022

# Environment variables to declare :
#     - SERVICE : name of the service (example : hastebin)
#     - EXPIRE  : set number of seconds to expire keys (example : 2592000)
#     - URL_LOKI : loki service URL (example : http://ip:3100/loki/api/v1/push)
#     - FQDN : fully qualified domain name (example : hastebin.domain.tld)
#     - NETWORK_APP : application network name
#     - NETWORK_DATA : data network name

# Work with Portainer

version: "3.3"
services:
  gitea:
    image: gitea/gitea:latest
    environment:
      USER_UID: $PUID
      USER_GID: $PGID
      USER: git
    healthcheck:
      test: wget --spider 'http://localhost:3000'
      interval: 1m
      timeout: 30s
      retries: 3
    deploy:
      placement:
        constraints:
        - node.role == worker
        - node.labels.general == true
      update_config:
        delay: 30s
      restart_policy:
        condition: on-failure
        max_attempts: 5
      labels:
        - traefik.enable=true
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.$SERVICE.entrypoints=https
        - traefik.http.routers.$SERVICE.rule=Host(`$FQDN`)
        - traefik.http.services.$SERVICE.loadbalancer.server.port=3000
        - traefik.docker.network=$NETWORK_APP
    logging:
      driver: loki
      options:
        loki-url: "$URL_LOKI"
        loki-external-labels: service={{.Name}}
    volumes:
      - $DATA_LOCATION/data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - default

networks:
  default:
    external:
      name: ${NETWORK_APP}
