# Docker-compose provided by Kevin Allioli
# Last update : /03/2022

# Environment variables to declare :
#     - SERVICE : name of the service (example : hastebin)
#     - EXPIRE  : set number of seconds to expire keys (example : 2592000)
#     - URL_LOKI : loki service URL (example : http://ip:3100/loki/api/v1/push)
#     - FQDN : fully qualified domain name (example : hastebin.domain.tld)
#     - NETWORK_APP : application network name
#     - NETWORK_DATA : data network name

# Work with Portainer

version: "3.3"
services:
  redis:
    image: redis:latest
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 30
    deploy:
      placement:
        constraints: [node.role == worker]
      update_config:
        delay: 30s
      restart_policy:
        condition: on-failure
        max_attempts: 5
      labels:
        - traefik.enable=false
    logging:
      driver: loki
      options:
        loki-url: "$URL_LOKI"
        loki-external-labels: service={{.Name}}
    networks:
      - default1

  hastebin:
    image: rlister/hastebin
    environment:
      STORAGE_TYPE: redis
      STORAGE_HOST: redis
      STORAGE_EXPIRE_SECONDS: $EXPIRE
    healthcheck:
      test: wget -s 'http://localhost:7777'
      interval: 1m
      timeout: 30s
      retries: 3
    deploy:
      placement:
        constraints: [node.role == worker]
      update_config:
        delay: 30s
      restart_policy:
        condition: on-failure
        max_attempts: 5
      labels:
        - traefik.enable=true
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.$SERVICE.entrypoints=https
        - traefik.http.routers.$SERVICE.rule=Host(`$FQDN`)
        - traefik.http.services.$SERVICE.loadbalancer.server.port=7777
        - traefik.docker.network=$NETWORK_APP
    logging:
      driver: loki
      options:
        loki-url: "$URL_LOKI"
        loki-external-labels: service={{.Name}}
    depends_on:
      - redis
    networks:
      - default
      - default1

networks:
  default:
    external:
      name: ${NETWORK_APP}
  default1:
    external:
      name: ${NETWORK_DATA}