# Docker-compose provided by Kevin Allioli
# Last update : 02/06/2022

# Environment variables to declare :
#     - SERVICE : name of the service (example : kanboard)
#     - DB_USER : database user (example : kanboard)
#     - DB_PASS : database password
#     - DB_HOST : database hostname (example : mariadb)
#     - DB_NAME : database name (example : kanboard)
#     - URL_LOKI : loki service URL (example : http://ip:3100/loki/api/v1/push)
#     - FQDN : fully qualified domain name (example : kanboard.domain.tld)
#     - DATA_LOCATION : location of service data (example /app/"service")
#     - NETWORK_APP : application network name
#     - NETWORK_DATA : data network name

# Work with Portainer

version: '3.3'
services:
  kanboard:
    image: kanboard/kanboard:latest
    environment:
      - DATABASE_URL=mysql://$DB_USER:$DB_PASS@$DB_HOST/$DB_NAME
    deploy:
      constraints:
        - node.role == worker
        - node.labels.general == true
      update_config:
        delay: 30s
      restart_policy:
        condition: on-failure
        max_attempts: 5
      labels:
        - traefik.enable=true
        - traefik.docker.network=$NETWORK_APP
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.$SERVICE.entrypoints=https
        - traefik.http.routers.$SERVICE.rule=Host(`$FQDN`)
        - traefik.http.services.$SERVICE.loadbalancer.server.port=80
    logging:
      driver: loki
      options:
        loki-url: "$URL_LOKI"
        loki-external-labels: service={{.Name}}
    volumes:
      - $DATA_LOCATION/data:/var/www/app/data
      - $DATA_LOCATION/plugins:/var/www/app/plugins
    networks:
      - default

networks:
  default:
    external:
      name: ${NETWORK_APP}

