# Docker-compose provided by Kevin Allioli
# Last update : 10/05/2022

# Environment variables to declare :
#     - SERVICE : name of the service (example : n8n)
#     - DB_USER : database user (example : n8n)
#     - DB_PASS : database password
#     - DB_HOST : database hostname (example : postgresql)
#     - DB_NAME : database name (example : n8n)
#     - DB_PORT : database serve port (example : 5432)
#     - URL_LOKI : loki service URL (example : http://ip:3100/loki/api/v1/push)
#     - FQDN : fully qualified domain name (example : n8n.domain.tld)
#     - NETWORK_APP : application network name
#     - NETWORK_DATA : data network name

# Work with Portainer

version: '3.3'
services:
  n8n:
    image: n8nio/n8n
    command: /bin/sh -c "sleep 5; n8n start"
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=$DB_HOST
      - DB_POSTGRESDB_PORT=$DB_PORT
      - DB_POSTGRESDB_DATABASE=$DB_NAME
      - DB_POSTGRESDB_USER=$DB_USER
      - DB_POSTGRESDB_PASSWORD=$DB_PASS
    deploy:
      placement:
        constraints:
        - node.role == worker
        - node.labels.general == true
      update_config:
        delay: 30s
      restart_policy:
        condition: on-failure
        max_attempts: 5
      labels:
        - traefik.enable=true
        - traefik.docker.network=$NETWORK_APP
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.$SERVICE.entrypoints=https
        - traefik.http.routers.$SERVICE.rule=Host(`$FQDN`)
        - traefik.http.services.$SERVICE.loadbalancer.server.port=5678
    healthcheck:
      test: grep -qr "node" /proc/*/status || exit 1
      interval: 1m
      timeout: 30s
      retries: 3
    logging:
      driver: loki
      options:
        loki-url: "$URL_LOKI"
        loki-external-labels: service={{.Name}}
    volumes:
      - $DATA_LOCATION:/home/node/.n8n
    networks:
      - default

networks:
  default:
    external:
      name: ${NETWORK_APP}